// ---------------------------------------------------------------------------
// Module 7 — Search & Analytics
// Actionable, AI-powered insights through natural language interaction
// and automated reporting.
// ---------------------------------------------------------------------------

import type { BaseEntity, Currency, DateRange } from './common';

// ---- Spend Dashboard (FR-7.2) -------------------------------------------

/**
 * Top-level spend dashboard aggregating data from the orchestration layer
 * and backend ERP. Supports drill-down to transaction level.
 */
export interface SpendDashboard {
  /** Reporting period. */
  period: DateRange;
  /** Total managed spend in the period. */
  totalSpend: Currency;
  /** Total spend year-to-date. */
  totalSpendYTD: Currency;
  /** Number of active suppliers. */
  activeSupplierCount: number;
  /** Number of active contracts. */
  activeContractCount: number;
  /** Number of POs issued in the period. */
  poCount: number;
  /** Percentage of spend under contract. */
  underContractPercent: number;
  /** Percentage of spend through preferred suppliers. */
  preferredSupplierPercent: number;
  /** Maverick / off-contract spend percentage. */
  maverickSpendPercent: number;

  // Breakdowns
  spendByCategory: SpendByCategory[];
  spendBySupplier: SpendByEntity[];
  spendByDepartment: SpendByEntity[];
  spendByRegion: SpendByEntity[];
  spendByBuyingChannel: SpendByEntity[];

  // Trends
  monthlySpendTrend: TrendData[];
  /** Savings vs. target progress. */
  savingsProgress: SavingsProgress;

  // Top-N lists
  topSuppliersBySpend: SpendByEntity[];
  topCategoriesBySpend: SpendByCategory[];
  /** Contracts expiring within 90 days. */
  upcomingExpirations: ExpiringContract[];

  generatedAt: string;
}

/**
 * Spend breakdown by procurement category.
 */
export interface SpendByCategory {
  category: string;
  subcategory?: string;
  amount: Currency;
  /** Percentage of total spend. */
  percentOfTotal: number;
  /** Change vs. previous period (positive = increase). */
  periodOverPeriodChange: number;
  transactionCount: number;
  supplierCount: number;
  /** Percentage under contract. */
  contractCoverage: number;
}

/** Generic spend breakdown by a named entity (supplier, dept, region, etc.). */
export interface SpendByEntity {
  id: string;
  name: string;
  amount: Currency;
  percentOfTotal: number;
  periodOverPeriodChange: number;
  transactionCount: number;
}

export interface ExpiringContract {
  contractId: string;
  contractNumber: string;
  title: string;
  supplierName: string;
  expirationDate: string;
  annualValue: Currency;
  autoRenew: boolean;
  daysUntilExpiry: number;
}

// ---- Savings Waterfall (FR-7.5) ------------------------------------------

/**
 * Savings waterfall tracking and visualisation.
 * Attributes savings across negotiation, compliance, process efficiency,
 * and demand management categories.
 */
export interface SavingsWaterfall {
  period: DateRange;
  /** Total realised savings in the period. */
  totalRealisedSavings: Currency;
  /** Total identified (pipeline) savings. */
  totalIdentifiedSavings: Currency;
  /** Savings target for the period. */
  savingsTarget: Currency;
  /** Achievement rate vs. target (0-1). */
  achievementRate: number;
  /** Per-category breakdown. */
  categories: SavingsCategory[];
  /** Monthly progression. */
  monthlyProgression: MonthlySavings[];
  /** Per-agent contribution to savings. */
  agentContributions?: AgentSavingsContribution[];
}

export interface SavingsCategory {
  name: 'negotiation' | 'compliance' | 'process_efficiency' | 'demand_management'
    | 'supplier_consolidation' | 'contract_optimization' | 'other';
  realisedAmount: Currency;
  identifiedAmount: Currency;
  percentOfTotal: number;
  projectCount: number;
}

export interface MonthlySavings {
  month: string; // YYYY-MM
  realisedAmount: Currency;
  identifiedAmount: Currency;
  cumulativeRealised: Currency;
  cumulativeTarget: Currency;
}

export interface AgentSavingsContribution {
  agentType: string;
  agentName: string;
  savingsGenerated: Currency;
  transactionsProcessed: number;
}

export interface SavingsProgress {
  targetAmount: Currency;
  realisedAmount: Currency;
  identifiedAmount: Currency;
  achievementPercent: number;
  projectedYearEnd: Currency;
  onTrack: boolean;
}

// ---- Predictive Analytics (FR-7.6) --------------------------------------

/**
 * Predictive analytics results generated by the Spend Analytics Agent (A11).
 */
export interface PredictiveAnalytics {
  /** Reporting context. */
  period: DateRange;
  /** Spend forecast for upcoming periods. */
  spendForecast: ForecastDataPoint[];
  /** Predicted supplier risk changes. */
  riskPredictions: RiskPrediction[];
  /** Anomalous spending patterns detected. */
  spendAnomalies: SpendAnomaly[];
  /** Upcoming contract actions requiring attention. */
  contractActions: ContractAction[];
  /** Demand-side predictions (budget utilisation). */
  budgetUtilisationForecast: BudgetForecast[];
  /** Confidence in overall predictions (0-1). */
  overallConfidence: number;
  modelVersion: string;
  generatedAt: string;
}

export interface ForecastDataPoint {
  period: string; // YYYY-MM
  predictedAmount: Currency;
  lowerBound: Currency;
  upperBound: Currency;
  confidence: number;
  /** Primary drivers of the forecast. */
  drivers: string[];
}

export interface RiskPrediction {
  supplierId: string;
  supplierName: string;
  predictedRiskChange: 'increase' | 'decrease' | 'stable';
  currentRiskScore: number;
  predictedRiskScore: number;
  /** Timeline of the predicted change. */
  timeframe: string;
  factors: string[];
  confidence: number;
}

export interface SpendAnomaly {
  id: string;
  type: 'unusual_volume' | 'price_spike' | 'new_supplier_surge' | 'category_shift'
    | 'duplicate_payment' | 'off_contract' | 'budget_overrun';
  severity: 'low' | 'medium' | 'high';
  description: string;
  affectedCategory?: string;
  affectedSupplierId?: string;
  affectedSupplierName?: string;
  amount?: Currency;
  detectedAt: string;
  /** Whether this anomaly has been reviewed. */
  reviewed: boolean;
  reviewedBy?: string;
  resolution?: string;
}

export interface ContractAction {
  contractId: string;
  contractNumber: string;
  actionType: 'renewal_decision' | 'renegotiation' | 'termination_notice' | 'compliance_review';
  dueDate: string;
  estimatedImpact: Currency;
  recommendation: string;
  urgency: 'low' | 'medium' | 'high';
}

export interface BudgetForecast {
  budgetId: string;
  budgetName: string;
  department: string;
  allocatedAmount: Currency;
  predictedSpend: Currency;
  utilisationPercent: number;
  /** Whether budget is predicted to be exceeded. */
  overrunPredicted: boolean;
  overrunAmount?: Currency;
}

// ---- Report Subscriptions (FR-7.8) --------------------------------------

/**
 * Scheduled automated report generation and distribution.
 * Supports PDF, Excel, PowerPoint export formats.
 */
export interface ReportSubscription extends BaseEntity {
  name: string;
  description?: string;
  /** Type of report. */
  reportType: ReportType;
  /** Cron expression or human-readable schedule. */
  schedule: string;
  /** Timezone for schedule execution. */
  timezone: string;
  /** Parameters / filters for the report. */
  parameters: Record<string, unknown>;
  /** Output format. */
  format: 'pdf' | 'excel' | 'powerpoint' | 'csv';
  /** Delivery method. */
  deliveryMethod: 'email' | 'dashboard' | 'sftp' | 'api';
  /** Recipients for email delivery. */
  recipients: string[];
  /** Whether the subscription is active. */
  isActive: boolean;
  /** Timestamp of the last successful run. */
  lastRunAt?: string;
  lastRunStatus?: 'success' | 'failed' | 'partial';
  nextRunAt?: string;
}

export type ReportType =
  | 'spend_summary'
  | 'savings_waterfall'
  | 'contract_expiration'
  | 'supplier_performance'
  | 'compliance_status'
  | 'agent_performance'
  | 'budget_utilisation'
  | 'risk_assessment'
  | 'esg_scorecard'
  | 'custom';

// ---- Dashboard & Widgets (FR-7.4) ---------------------------------------

/**
 * A user-created or system-provided dashboard composed of widgets.
 */
export interface DashboardWidget {
  id: string;
  /** Widget display type. */
  type: WidgetType;
  title: string;
  description?: string;
  /** Grid position and size. */
  layout: WidgetLayout;
  /** Data source configuration. */
  dataSource: WidgetDataSource;
  /** Visual configuration (colors, labels, etc.). */
  visualConfig?: Record<string, unknown>;
  /** Refresh interval in seconds (0 = manual only). */
  refreshIntervalSec: number;
}

export type WidgetType =
  | 'kpi_card'
  | 'bar_chart'
  | 'line_chart'
  | 'pie_chart'
  | 'donut_chart'
  | 'table'
  | 'trend_line'
  | 'waterfall'
  | 'heatmap'
  | 'gauge'
  | 'scatter_plot'
  | 'map';

export interface WidgetLayout {
  /** Column position (0-based). */
  col: number;
  /** Row position (0-based). */
  row: number;
  /** Width in grid units. */
  width: number;
  /** Height in grid units. */
  height: number;
}

export interface WidgetDataSource {
  /** Named data endpoint or query. */
  endpoint: string;
  /** Filter parameters. */
  filters?: Record<string, unknown>;
  /** Aggregation mode. */
  aggregation?: 'sum' | 'avg' | 'count' | 'min' | 'max';
  /** Grouping dimension. */
  groupBy?: string;
  /** Time granularity. */
  granularity?: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'yearly';
}

/**
 * A single KPI card displayed on dashboards.
 */
export interface KPICard {
  id: string;
  title: string;
  /** Primary numeric value. */
  value: number;
  /** Unit / suffix (e.g. "%", "days", "$"). */
  unit: string;
  /** Target value for comparison. */
  target?: number;
  /** Change vs. previous period. */
  change?: number;
  changePercent?: number;
  /** Trend direction indicator. */
  trend: 'up' | 'down' | 'flat';
  /** Colour coding based on performance vs. target. */
  status: 'good' | 'warning' | 'critical' | 'neutral';
  /** Sparkline data for inline trending. */
  sparkline?: number[];
}

// ---- Time Series & Velocity Metrics -------------------------------------

/**
 * Generic time-series data point used across analytics views.
 */
export interface TrendData {
  /** Time label (ISO date or period label). */
  label: string;
  value: number;
  /** Optional comparison value (e.g. same period last year). */
  comparisonValue?: number;
  /** Metadata for drill-down. */
  metadata?: Record<string, unknown>;
}

/**
 * Velocity metric measuring throughput and cycle time efficiency.
 * Used for operational performance dashboards.
 */
export interface VelocityMetric {
  name: string;
  description: string;
  /** Current period value. */
  current: number;
  /** Previous period value. */
  previous: number;
  /** Target value. */
  target: number;
  /** Unit of measure. */
  unit: string;
  /** Change percentage. */
  changePercent: number;
  /** Trend over multiple periods. */
  trend: TrendData[];
  /** Status assessment. */
  status: 'on_target' | 'above_target' | 'below_target' | 'at_risk';
}
