properties:
  template:
    containers:
      - name: api
        image: acrprocgeniedev.azurecr.io/procgenie-api:v1.0.1
        probes:
          - type: Liveness
            tcpSocket:
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          - type: Readiness
            tcpSocket:
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          - type: Startup
            tcpSocket:
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 12
