export default () => ({
  app: {
    nodeEnv: process.env.NODE_ENV || 'development',
    port: parseInt(process.env.PORT, 10) || 3000,
    apiPrefix: process.env.API_PREFIX || 'api/v1',
    name: process.env.APP_NAME || 'ProcGenie',
    url: process.env.APP_URL || 'http://localhost:3000',
    corsOrigins: process.env.CORS_ORIGINS || 'http://localhost:3001',
  },
  database: {
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT, 10) || 5432,
    username: process.env.DB_USERNAME || 'procgenie',
    password: process.env.DB_PASSWORD || 'procgenie_secret',
    database: process.env.DB_DATABASE || 'procgenie_dev',
    ssl: process.env.DB_SSL === 'true',
    synchronize: process.env.DB_SYNCHRONIZE === 'true',
    logging: process.env.DB_LOGGING === 'true',
    maxConnections: parseInt(process.env.DB_MAX_CONNECTIONS, 10) || 100,
  },
  redis: {
    host: process.env.REDIS_HOST || 'localhost',
    port: parseInt(process.env.REDIS_PORT, 10) || 6379,
    password: process.env.REDIS_PASSWORD || undefined,
    db: parseInt(process.env.REDIS_DB, 10) || 0,
    ttl: parseInt(process.env.REDIS_TTL, 10) || 3600,
  },
  jwt: {
    secret: process.env.JWT_SECRET || 'change-me-in-production',
    expiresIn: process.env.JWT_EXPIRES_IN || '1h',
    refreshSecret: process.env.JWT_REFRESH_SECRET || 'change-refresh-in-production',
    refreshExpiresIn: process.env.JWT_REFRESH_EXPIRES_IN || '7d',
  },
  azure: {
    tenantId: process.env.AZURE_AD_TENANT_ID,
    clientId: process.env.AZURE_AD_CLIENT_ID,
    clientSecret: process.env.AZURE_AD_CLIENT_SECRET,
    redirectUri: process.env.AZURE_AD_REDIRECT_URI,
    storage: {
      account: process.env.AZURE_STORAGE_ACCOUNT,
      key: process.env.AZURE_STORAGE_KEY,
      container: process.env.AZURE_STORAGE_CONTAINER || 'procgenie-documents',
    },
  },
  ai: {
    azureOpenAiApiKey: process.env.AZURE_OPENAI_API_KEY,
    azureOpenAiEndpoint: process.env.AZURE_OPENAI_ENDPOINT,
    azureOpenAiDeploymentName: process.env.AZURE_OPENAI_DEPLOYMENT_NAME || 'gpt-4o',
    azureOpenAiApiVersion: process.env.AZURE_OPENAI_API_VERSION || '2024-12-01-preview',
    maxTokens: parseInt(process.env.AZURE_OPENAI_MAX_TOKENS, 10) || 4096,
  },
  bull: {
    prefix: process.env.BULL_QUEUE_PREFIX || 'procgenie',
    defaultAttempts: parseInt(process.env.BULL_QUEUE_DEFAULT_ATTEMPTS, 10) || 3,
    defaultBackoff: parseInt(process.env.BULL_QUEUE_DEFAULT_BACKOFF, 10) || 5000,
  },
  features: {
    aiAnalysis: process.env.FEATURE_AI_ANALYSIS === 'true',
    esgScoring: process.env.FEATURE_ESG_SCORING === 'true',
    predictiveAnalytics: process.env.FEATURE_PREDICTIVE_ANALYTICS === 'true',
    autoApproval: process.env.FEATURE_AUTO_APPROVAL === 'true',
  },
  tenancy: {
    defaultTenantId: process.env.DEFAULT_TENANT_ID || 'default',
  },
});
